package com.br.jetpacktest.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF3C691B)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFBCF293)
val md_theme_light_onPrimaryContainer = Color(0xFF0B2000)
val md_theme_light_secondary = Color(0xFF56624B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDAE7CA)
val md_theme_light_onSecondaryContainer = Color(0xFF141E0C)
val md_theme_light_tertiary = Color(0xFF7D5700)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDEAB)
val md_theme_light_onTertiaryContainer = Color(0xFF271900)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFDFDF5)
val md_theme_light_onBackground = Color(0xFF1A1C18)
val md_theme_light_surface = Color(0xFFFDFDF5)
val md_theme_light_onSurface = Color(0xFF1A1C18)
val md_theme_light_surfaceVariant = Color(0xFFE0E4D6)
val md_theme_light_onSurfaceVariant = Color(0xFF44483E)
val md_theme_light_outline = Color(0xFF74796D)
val md_theme_light_inverseOnSurface = Color(0xFFF1F1EA)
val md_theme_light_inverseSurface = Color(0xFF2F312C)
val md_theme_light_inversePrimary = Color(0xFFA1D57A)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF3C691B)
val md_theme_light_outlineVariant = Color(0xFFC4C8BB)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFA1D57A)
val md_theme_dark_onPrimary = Color(0xFF173800)
val md_theme_dark_primaryContainer = Color(0xFF255102)
val md_theme_dark_onPrimaryContainer = Color(0xFFBCF293)
val md_theme_dark_secondary = Color(0xFFBECBAF)
val md_theme_dark_onSecondary = Color(0xFF293420)
val md_theme_dark_secondaryContainer = Color(0xFF3F4A35)
val md_theme_dark_onSecondaryContainer = Color(0xFFDAE7CA)
val md_theme_dark_tertiary = Color(0xFFFBBB42)
val md_theme_dark_onTertiary = Color(0xFF422C00)
val md_theme_dark_tertiaryContainer = Color(0xFF5F4100)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDEAB)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C18)
val md_theme_dark_onBackground = Color(0xFFE3E3DC)
val md_theme_dark_surface = Color(0xFF1A1C18)
val md_theme_dark_onSurface = Color(0xFFE3E3DC)
val md_theme_dark_surfaceVariant = Color(0xFF44483E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C8BB)
val md_theme_dark_outline = Color(0xFF8E9286)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C18)
val md_theme_dark_inverseSurface = Color(0xFFE3E3DC)
val md_theme_dark_inversePrimary = Color(0xFF3C691B)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFA1D57A)
val md_theme_dark_outlineVariant = Color(0xFF44483E)
val md_theme_dark_scrim = Color(0xFF000000)


val md_forgot_password = Color(0xFF0098FF)


val seed = Color(0xFF3D6A1C)
val Primary = Color(0xFF92A3FD)
val Secondary = Color(0xFF9DCEFF)
val TextColor = Color(0xFF1D1617)
val AccentColor = Color(0xFFC58BF2)
val GrayColor = Color(0xFF7B6F72)
val WhiteColor = Color(0xFFFFFFFF)
val BgColor = Color(0xFFF7F8F8)
